#!/usr/bin/python3

from flask import Flask, render_template, request
from flask_ngrok import run_with_ngrok
import sys, os, yaml, json, jjcli

fconf = sys.argv[1]
conf = yaml.load( open(fconf).read() )

app = Flask(__name__)
#FIXME
#run_with_ngrok(app)

c = jjcli.clfilter(opt="cjh")
print(c)

@app.route('/quest',methods = ['GET','POST'])
def quest():
    if request.method == 'GET':
        return list2form (conf)

    if request.method == 'POST':
        form2file(conf, request.form)
        return mostra_request (conf, request.form)


def list2form(l:list)->str:
    title,*l2 = l
    h = f"<h1>{title}</h1>\n<form method='post'> <ul>"
    fim = "<input type=submit value='done'/> </ul></form>"

    for dic in l2:
        id = dic['id'] # name
        t  = dic.get('t','str') # types
        op = dic.get('o') # options
        d  = dic.get('h','') # description, helper
        r  = dic.get('req',False) # required
        req = 'required' if r else ''

        if t == 'str':
            h += f"<li> {id}: <input type='text' name='{id}' {req} /> </li> <p>{d}</p>\n"
        if t == 'radio': # selects on of diferent buttons 
            h += f'<li>{id}: <br/>'
            for elem in op:
                h += f"<input type='radio' name='{id}' value='{elem}' {req} >  {elem}</input> <br/>"
            h += f'</li>  <p>{d}</p>\n'
        if t == 'check':# checkbox buttons
            h += f'<li>{id}: <br/>'
            for elem in op:
                h += f"<input type='checkbox' name='{id}' value='{elem}' >  {elem}</input> <br/>"
            h += f'</li> <p>{d}</p>\n'
        # upload files
    return h + fim

    
#takes a form and a list os dicts(from yaml) and stores it in json, csv files
def form2file(l:list,d:list)->str:
    fdict = forms2dict(d)
    fcsv  = forms2csv(l,d)

    #path to yamell: fconf
    #extracting the file name and path from fconf (first argument)
    lp = fconf.split(sep='/') #list with the path
    if len(lp) > 1:
        name = lp[-1][:-5] # from: 'path/path/name.yaml' returns: 'name'
        path = '/'.join(lp[:-1])+'/' #path without the file
    else:
        name = lp [0][:-5]
        path = ''
    
    lId = listId(l) # list of dentifiers 

    # csv
    if os.path.exists(path+name+'.csv'):
        f = open(path+name+'.csv','a')
        f.write(fcsv)
        f.write('\n')
        f.close()
    else:
        f = open(path+name+'.csv','a')
        f.write(','.join(lId)+'\n')
        f.write(fcsv)
        f.write('\n')
        f.close()
    #json.dumps(k) to tranforms a dict insto json


#making the "recieved" html for the POST method
def mostra_request(l:list,d:list)->str:
    title,*l2 = l
    h   = f'<h1> Received : {title} </h1> <ul>'
    fim = '</ul>'

    for dic in l2:
        id = dic['id'] # name
        t  = dic.get('t','str') # types
        if t == 'check':
            h += f'<li> {id}: '
            h += str.join(', ',d.getlist(id))
            h += '</li>'
        else:
            h += f"<li> {id}: {d[id]} </li>\n"
    return h + fim

#forms to coma separated values
def forms2csv(l:list,d:dict)->str:
    title,*l2 = l
    lId = listId(l) # list of identifiers
    acc = []
    for id in lId:
        lo = d.getlist(id)
        if not lo: #lo == []
            acc.append('')
        if len(lo) == 1: #one argument
            acc.append(csv(lo[0]))
        if len(lo) > 1: # multiple answers
            acc.append(csv(', '.join(lo)))
    return ','.join(acc)

#string to csv
def csv (word:str)->str:
    wordaux = ''
    if '"' in word:
        for l in word:
            if l == '"':
                wordaux += '"'+ '"'
            else:
                wordaux += l
    if wordaux: # wordaux != null
        wordcsv = wordaux
    else:
        wordcsv = word
    if ',' in wordcsv or '"' in wordcsv:
        wordcsv = '"'+wordcsv+'"'
    return wordcsv

#convert a form to a dict
def forms2dict(l:list)->dict:
    acc = {}
    for id in l:
        lo = l.getlist(id)
        if len(lo) == 1:
            acc[id] = lo[0]
        else:
            acc[id] = lo
    return acc
    
def listId(l:list)->list:
    title,*l2 = l
    lacc = [] # list of identifiers
    for dic in l2:
        lacc.append(dic['id'])
    return lacc

if __name__ == '__main__':
    app.run()

# yaml.load ↓
#['Torneio de xadrez viii edição Braga', {'id': 'nome', 't': 'str', 'h': 'descriçao nome completo', 'req': True}, {'id': 'sexo', 't': 'radio', 'o': ['masculino', 'feminino'], 'h': 'atençao abcdefghijklmnopqrstuvwxy', 'req': True}, {'id': 'checkbox', 't': 'check', 'o': ['vaca', 'gato', 'crocodilo', 'bicho pau']}]
# form request
#ImmutableMultiDict([('nome', 'joao afonsoa alvim oliveida dias de almeida'), ('sexo', 'masculino'), ('checkbox', 'vaca'), ('checkbox', 'gato'), ('checkbox', 'crocodilo'), ('checkbox', 'bicho pau')])
#json dumps
#{"nome": "joao afonsoa alvim oliveida dias de almeida", "sexo": "masculino", "checkbox": "vaca"}
