#!/usr/bin/python3

from flask import Flask, render_template, request
import sys,os,yaml,json

fconf = sys.argv[1]
conf = yaml.load( open(fconf).read() )
#print(conf)

app = Flask(__name__)


@app.route('/quest',methods = ['GET','POST'])
def quest():
    if request.method == 'GET':
        return list2form2 (conf)

    if request.method == 'POST':
        return mostra_request2 (conf,request.form)


def list2form2(l:list)->str:
    titulo,*l2 = l
    h = f"<h1>{titulo}</h1>\n<form method='post'> <ul>"
    fim = "<input type=submit value='done'/> </ul></form>"

    for dic in l2:
        id = dic['id'] # name
        t  = dic.get('t','str') # types
        op = dic.get('o') # options
        d  = dic.get('h','') # description, helper
        r  = dic.get('req',False) # required
        
        req = 'required' if r else ''

        if t == 'str':
            h += f"<li> {id}: <input type='text' name='{id}' {req} /> </li> <p>{d}</p>\n"

        if t == 'radio': # selects on of diferent buttons 
            h += f'<li>{id}: <br/>'
            for elem in op:
                h += f"<input type='radio' name='{id}' value='{elem}' {req} >  {elem}</input> <br/>"
            h += f'</li>  <p>{d}</p>\n'

        if t == 'check':# checkbox buttons
            h += f'<li>{id}: <br/>'
            for elem in op:
                h += f"<input type='checkbox' name='{id}' value='{elem}' >  {elem}</input> <br/>"
            h += f'</li> <p>{d}</p>\n'
        # upload files
    return h + fim

    
def mostra_request2(l:list,d:list)->str:
    
    
    print("\n\n")
    print(l)
    print("\n\n")
    print(d)
    print("\n\n")
    print("\n\n")
    k = fomrs2dict(d)
    print(json.dumps(k))
    print("\n\n")

    titulo,*l2 = l

    h   = f'<h1>recebido : {titulo} </h1> <ul>'
    fim = '</ul>'


    for dic in l2:

        id = dic['id'] # name
        t  = dic.get('t','str') # types

        if t == 'check':
            h += f'<li> {id}: '
            h += str.join(' | ',d.getlist(id))
            h += '</li>'

        else:
            h += f"<li> {id}: {d[id]} </li>\n"
    return h + fim


#['Torneio de xadrez viii edição Braga', {'id': 'nome', 't': 'str', 'h': 'descriçao nome completo', 'req': True}, {'id': 'sexo', 't': 'radio', 'o': ['masculino', 'feminino'], 'h': 'atençao abcdefghijklmnopqrstuvwxy', 'req': True}, {'id': 'checkbox', 't': 'check', 'o': ['vaca', 'gato', 'crocodilo', 'bicho pau']}]



#ImmutableMultiDict([('nome', 'joao afonsoa alvim oliveida dias de almeida'), ('sexo', 'masculino'), ('checkbox', 'vaca'), ('checkbox', 'gato'), ('checkbox', 'crocodilo'), ('checkbox', 'bicho pau')])



#{"nome": "joao afonsoa alvim oliveida dias de almeida", "sexo": "masculino", "checkbox": "vaca"}

def fomrs2dict(l:list)->dict:
    acc = {}
    for id in l:
        lo = l.getlist(id)
        if len(lo) == 1:
            acc[id] = lo[0]
        else:
            acc[id] = lo
    return acc
    

#if __name__ == '__main__':
app.run()
